spring:
  application:
    name: scheduler-service

  kafka:
    bootstrap-servers: kafka:9092
#    bootstrap-servers: host.docker.internal:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true
    enabled: true
    topics:
      project-status-changed: DEV_project_status_changed_1_0_pu

server:
  port: 8081
